version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20   # Ensure the correct Docker version if available in the environment

    commands:
      - echo Installing necessary tools...
      - apt-get update
      - apt-get install -y curl unzip docker.io
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 008971637333.dkr.ecr.ca-central-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t assignment3 .
      - docker tag assignment3:latest 008971637333.dkr.ecr.ca-central-1.amazonaws.com/assignment3:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 008971637333.dkr.ecr.ca-central-1.amazonaws.com/assignment3:latest
